### ISSUE TITLE
RSP SW 2.0 support

### ISSUE THREAD

**Issue by GithubPrankster** [rt64/rt64#49]
Used by Mischief Makers (2.0H for rev1 specifically) and other games.
![image](https://github.com/rt64/rt64/assets/33995085/98526e03-71bd-4a38-aceb-f5fd57287cce)

**Comment by DarioSamo** [comment]
Can you list some of the games that use it to verify it's working properly?

**Comment by Calinou** [comment]
> Can you list some of the games that use this version in particular to verify it's working properly?

Space Station Silicon Valley (NTSC-U) seems to use the same RSP SW version:

```
Unable to find a matching GBI in the current database. This game is not supported in HLE.
Detected name in data: RSP SW Version: 2.0H, 02-12-97
```

**Comment by DarioSamo** [comment]
Should be in the database now, although it's not been verified if it works correctly yet.
