### ISSUE TITLE
Linux Support - Steam Deck 

### ISSUE THREAD

**Issue by aztects84** [rt64/rt64#7]
I know the Majora's Mask has Linux Support, but will the decompiler have Linux Support on the steam deck, or will it just have to recompile on windows and if so... How to play other N64 Roms on the Steam Deck? Hope this question makes sense.

**Comment by DarioSamo** [comment]
Hello, this is not the recompiler repository. Please ask relevant questions in https://github.com/Mr-Wiseguy/N64Recomp.
