### ISSUE TITLE
Check for currently installed driver version on Windows when Initializing D3D12 device

### ISSUE THREAD

**Issue by DeaTh-G** [rt64/rt64#77]
During the initialization step of D3D12 it should look up the currently installed and used DriverVersion, to avoid false reports from out of date GPU drivers.
The UUID for the currently used GPU driver can be extracted from the values found in the registry at `HKEY_LOCAL_MACHINE\HARDWARE\DEVICEMAP\VIDEO`. Using this ID its possible to lookup the versions contained in `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\DirectX\`, whilst comparing against the AdapterLuid in `DXGI_ADAPTER_DESC1`.
After that it is possible to extract the `DriverVersion` which can be decoded as such:
https://stackoverflow.com/a/56960922

**Comment by DarioSamo** [comment]
This is now part of this [PR](https://github.com/rt64/rt64/pull/88), although using the API method suggested by the[ other commenter](https://stackoverflow.com/a/74799601) in that thread gave the same result as checking the registry.
